In [3]:
import numpy as np
#To use numpy frequently we're assigning it a short form.
#instead of adding whole numpy word for every line - we can use np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr_tup = np.array((1,2,3,4))
print(arr_tup)
print(type(arr_tup))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
one_d_array = np.array([1,2,3,4])
print(one_d_array)

[1 2 3 4]


In [4]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [6]:
two_d_array.ndim

2

In [7]:
threed_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(threed_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
three_d_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(three_d_array)
three_d_array.astype
three_d_array.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(3, 2, 3)

Array Inspection:
Numpy Array follows below operations:
- ndarray.shape (Matrix form)
- ndarray.ndim (Dimensions)
- ndarray.size
- ndarray.dtype (Data Type)
- ndarray.astype (

In [9]:
two_d_array.shape

(2, 3)

In [10]:
one_d_array = np.array([1,2,3,4])
one_d_array.shape

(4,)

In [11]:
#Shape of an Array
#For 1-D Array - (No. of 0-D Arrays)
#For 2-D Array - (No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)
#For 3-D Array - (No. of 2-D Array in 3-D, No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)