In [2]:
import numpy as np
#To use numpy frequently we're assigning it a short form.
#instead of adding whole numpy word for every line - we can use np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr_tup = np.array((1,2,3,4))
print(arr_tup)
print(type(arr_tup))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
one_d_array = np.array([1,2,3,4])
print(one_d_array)

[1 2 3 4]


In [ ]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
two_d_array.ndim

2

In [ ]:
threed_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(threed_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
three_d_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(three_d_array)
three_d_array.astype
three_d_array.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(3, 2, 3)

Array Inspection:
Numpy Array follows below operations:
- ndarray.shape (Matrix form)
- ndarray.ndim (Dimensions)
- ndarray.size
- ndarray.dtype (Data Type)
- ndarray.astype (

In [ ]:
two_d_array.shape

(2, 3)

In [ ]:
one_d_array = np.array([1,2,3,4])
one_d_array.shape

(4,)

In [ ]:
#Shape of an Array
#For 1-D Array - (No. of 0-D Arrays)
#For 2-D Array - (No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)
#For 3-D Array - (No. of 2-D Array in 3-D, No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)

Day 2 of Numpy

In [2]:
#4-D Array
array = np.array([
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]],
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]],
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]]
                 ])
print(array.shape, array.size, array.dtype, array.itemsize,
array.ndim)

(3, 2, 2, 4) 48 int64 8 4


In [3]:
#Data type of an Array
l = np.array([1,2,5,"Dilip", True, False, "Ungaaaaaa", 1.256])
print(l)
print(l.dtype)

#Array.astype
m = np.array([1,2,5,1])
print(m)
print(m.dtype)
m_new = m.astype("U32")
print(m_new)
print(m_new.dtype)

['1' '2' '5' 'Dilip' 'True' 'False' 'Ungaaaaaa' '1.256']
<U32
[1 2 5 1]
int64
['1' '2' '5' '1']
<U32


Why Numpy -
- Memory - takes less memory
- Performs much better than lists
- Functionality - Scipy & Numpy have optimized functions built in.

In [9]:
# Different ways to create random arrays

random_array = np.empty([5,3,4], dtype = int)
random_array

array([[[      94248324938142,                    0,
           119189669097008225,  7021800530361581568],
        [ 7598807797348065145,  7021238715563339375,
                 190898004852,    21798917532306546],
        [ 8214565722529071104,      176411486715941,
         -5876634563762556416,         169416327168]],

       [[   11384343394038642,  8214565723317600256,
          7955894451564445892,   680606493699699316],
        [        895265800193,    80627187664869234,
         -2738188568702615552,  2410116712426661381],
        [       1225978281984,     9132543580382322,
          8214565721019121664,  8030770093904363646]],

       [[ 7305985224698328178,  7810759579942609254,
          8318818562678813797,   117218934637208178],
        [ 8214565720918458368,       56564719288356,
          3707025443282711040,         225250902016],
        [ 7815263158108162266, -3858740455726301595,
           576751023507374080,   576751027802408961]],

       [[  576755426050246657, 

In [8]:
# Initialize with Zero
zero_array = np.zeros([5,3], dtype = int)
zero_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# Array with ones
one_array = np.ones([5,3], dtype = int)
one_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
arange = np.arange(10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arange = np.arange(10, 20)
arange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
x = np.arange(10,25, 2)
x

array([10, 12, 14, 16, 18, 20, 22, 24])

In [24]:
lsv = np.arange(25,45,3)
lsv

array([25, 28, 31, 34, 37, 40, 43])

In [27]:
#Linspace - Generates equidistant values inside the array
linspace = np.linspace(10,20,5, endpoint = False, retstep= True)
linspace

(array([10., 12., 14., 16., 18.]), 2.0)

In [30]:
#Random Function
random_array = np.random.random([5,3])
random_array

array([[0.72154932, 0.99757017, 0.59313236],
       [0.54196004, 0.51428321, 0.59400474],
       [0.21838695, 0.0461223 , 0.34743111],
       [0.89928419, 0.20009607, 0.90449996],
       [0.53310913, 0.07441226, 0.99747996]])

In [34]:
rand_array = np.random.randint(5,15, size = (3,2,4))
rand_array

array([[[ 9, 10,  5, 11],
        [13,  7, 13,  6]],

       [[13, 13, 12,  8],
        [ 6, 14,  8,  6]],

       [[ 6,  6, 12,  9],
        [ 6,  7,  9, 13]]])

In [39]:
#Indexing and Slicing in Array
a = np.random.random(10)
a

array([0.59380419, 0.51647705, 0.04410845, 0.86228722, 0.93922537,
       0.21781216, 0.39542541, 0.50023398, 0.00163715, 0.83849057])

In [40]:
a[::2]

array([0.59380419, 0.04410845, 0.93922537, 0.39542541, 0.00163715])

In [42]:
a[1:4:]

array([0.51647705, 0.04410845, 0.86228722])

In [45]:
#Slicing of a 2-D Array
two_d_array = np.array([[1,2,3,4],[5,6,7,8],[9,8,9,4]])
two_d_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
two_d_array[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [47]:
two_d_array[1:, 1:]

array([[6, 7, 8],
       [8, 9, 4]])

In [53]:
#For a 3-D Array
a = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]] ])
a[0:2, 1:,1:]

array([[[6, 7, 8]],

       [[6, 7, 8]]])

In [54]:
a = np.random.randint(5,15, size = (3,2,4))
a

array([[[13,  8,  7, 14],
        [ 6,  7, 10, 10]],

       [[ 9, 11, 10, 13],
        [ 6, 14,  7, 10]],

       [[ 6, 13,  5, 13],
        [ 6, 10, 12, 12]]])

In [56]:
a[1:, 1:2, 1:3]

array([[[14,  7]],

       [[10, 12]]])

In [57]:
#Transpose Function
transpose = np.array(np.random.randint(10,45, (8,2)))
transpose

array([[44, 23],
       [19, 21],
       [28, 21],
       [11, 11],
       [21, 21],
       [18, 38],
       [32, 14],
       [39, 19]])

In [58]:
np.transpose(transpose)

array([[44, 19, 28, 11, 21, 18, 32, 39],
       [23, 21, 21, 11, 21, 38, 14, 19]])

In [ ]:
#Remaining-----
#np.flatten

#basic operations

# np.add()
# np.substract()
# np.multiply
# no.divide
