In [1]:
import numpy as np
#To use numpy frequently we're assigning it a short form.
#instead of adding whole numpy word for every line - we can use np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr_tup = np.array((1,2,3,4))
print(arr_tup)
print(type(arr_tup))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
one_d_array = np.array([1,2,3,4])
print(one_d_array)

[1 2 3 4]


In [4]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [6]:
two_d_array.ndim

2

In [7]:
threed_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(threed_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
three_d_array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(three_d_array)
three_d_array.astype
three_d_array.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(3, 2, 3)

Array Inspection:
Numpy Array follows below operations:
- ndarray.shape (Matrix form)
- ndarray.ndim (Dimensions)
- ndarray.size
- ndarray.dtype (Data Type)
- ndarray.astype (

In [9]:
two_d_array.shape

(2, 3)

In [10]:
one_d_array = np.array([1,2,3,4])
one_d_array.shape

(4,)

In [11]:
#Shape of an Array
#For 1-D Array - (No. of 0-D Arrays)
#For 2-D Array - (No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)
#For 3-D Array - (No. of 2-D Array in 3-D, No. of 1-D Array in 2-D, No. of 0-D Array in 1-D)

Day 2 of Numpy

In [2]:
#4-D Array
array = np.array([
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]],
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]],
                 [[[1,2,3,4], [5,6,7,8]], [[9,5,6,4], [1,5,6,9]]]
                 ])
print(array.shape, array.size, array.dtype, array.itemsize,
array.ndim)

(3, 2, 2, 4) 48 int64 8 4


In [3]:
#Data type of an Array
l = np.array([1,2,5,"Dilip", True, False, "Ungaaaaaa", 1.256])
print(l)
print(l.dtype)

#Array.astype
m = np.array([1,2,5,1])
print(m)
print(m.dtype)
m_new = m.astype("U32")
print(m_new)
print(m_new.dtype)

['1' '2' '5' 'Dilip' 'True' 'False' 'Ungaaaaaa' '1.256']
<U32
[1 2 5 1]
int64
['1' '2' '5' '1']
<U32


Why Numpy -
- Memory - takes less memory
- Performs much better than lists
- Functionality - Scipy & Numpy have optimized functions built in.

Help on built-in module sys:

NAME
    sys

MODULE REFERENCE
    https://docs.python.org/3.10/library/sys.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to some objects used or maintained by the
    interpreter and to functions that interact strongly with the interpreter.
    
    Dynamic objects:
    
    argv -- command line arguments; argv[0] is the script pathname if known
    path -- module search path; path[0] is the script directory, else ''
    modules -- dictionary of loaded modules
    
    displayhook -- called to show results in an interactive session
    excepthook -- called to handle any uncaught exception other than SystemExit
      To customize pri